spring.application.name=Eduko
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orclpdb
spring.datasource.username=hr
spring.datasource.password=ahmed
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.messages.encoding=UTF-8
server.port=8081
token.secret=dfkjgsg'f;'bvbvbml;""::::@#$%4djfdj546g4g6800.35565@@##$$%%%^^^&&***(jfgjkgfDFGFDGFGbVBVBvb,...;5654{}{[]ZZZZxcc
token.duration=24h
spring.messages.basename=message/bundle
